# Generated by Django 5.0.7 on 2024-07-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cnm', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
